import type { Metadata } from "next";
import BlogHeader from "../components/BlogHeader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="px-[42px]">
        <BlogHeader />
        {children}
      </body>
    </html>
  );
}
