name: Synchronize to forked repo

on:
  push:
    branches:
      - develop
      - main

jobs:
  sync:
    name: Sync to forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add remote-url
        run: |
          git remote add forked-repo https://tnemnorivnelee:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/tnemnorivnelee/GamzaTechBlog-front
          git config user.name tnemnorivnelee
          git config user.email tnemnorivnelee@gmail.com

      - name: Push to forked repo
        run: |
          git push -f forked-repo ${{ github.ref_name }}

      - name: Clean up
        run: |
          git remote remove forked-repo
